### ISSUE TITLE
Frozen with big file & tabular output.

### ISSUE THREAD

**Issue by yifangt** [txje/spaghetti#1]
Hello, 
Very cool program! 
1) Can I ask what is the max file size (say m4 format) to handle? My file is ~ 100MB, it ran well at fresh try, but frozen whenever I tried to change any of the settings: identity/ overlap length / Edge aligned threshold.
2) Is it possible to get the final overlapping result to a tabular output?
Thanks a lot!

**Comment by txje** [comment]
Thanks
1) It depends on your computer. In my experience, tens of Mb is the point at which it become unusable. It's impressive that you managed to load a 100Mb file. That said, changing the filtering settings must go through all of the edges again and it may hang if you have a very large graph.
2) Possible, yes. But it's not on my short list of things to do. This is first and foremost a visualization tool and real data manipulation is probably better done with other tools.

**Comment by yifangt** [comment]
I tried the script of Jason Chin of Pacific Biosciences. The problem is the nodes name that are all changed losing all the real sequence ID.
You program can show the node ID implying the sequence ID are kept. I'd like to get your advice on the tabular output, if you have any experience, or ideas in mind. Thanks again!

**Comment by txje** [comment]
Neither this nor Jason Chin's script are supposed to be general-purpose assemblers. This visualization tools is designed only to show the graph structure and inform reasonable overlap parameters for further layout. To this end, canu (github.com/marbl/canu) is an excellent long read assembler.

**Comment by yifangt** [comment]
Thanks! I am going to give it a try with canu!
